### ISSUE TITLE
Branches are gone?

### ISSUE THREAD

**Issue by yqszxx** [JohnAZoidberg/riscv-edk2-docker#3]
Branch `riscv-virt-540-mod` of `riscv-edk2` and `riscv-virt-540-mod-opensbi0.9` of `riscv-edk2-platforms` are all gone.

So I just tried to build directly on master branches of upstream `edk2` and `edk2-platforms`, the resulting U540.fd worked in QEMU.

But when I tried to boot linux following [this tutorial](https://github.com/riscv-admin/riscv-uefi-edk2-docs#building-an-running), I found that `embeddedramdisk` command is missing, just like what is stated in [this issue](https://github.com/riscv-admin/riscv-uefi-edk2-docs/issues/3).

You suggested in riscv-admin/riscv-uefi-edk2-docs#3 to use this repo but missing branches stop me from getting a working build.

I also tried to mount a storage device containing linux kernel and rootfs as an SD card in sifive_u machine, but it didn't get recognized by EDK:

```
Shell> map -r
map: Status: Not Found
```

Any suggestions on how to build EDK to boot linux on QEMU sifive_u machine? Which repo and which branch?

By the way I'm trying to port EDK2 to sifive unmatched.

**Comment by JohnAZoidberg** [comment]
> By the way I'm trying to port EDK2 to sifive unmatched.

Awesome!

> So I just tried to build directly on master branches of upstream edk2 and edk2-platforms, the resulting U540.fd worked in QEMU.

Yes, all U540 (HW and QEMU) work is upstreamed in edk2 and edk2-platforms.

> But when I tried to boot linux following this tutorial, I found that embeddedramdisk command is missing, just like what is stated in this issue.

I can still see the branch here: https://github.com/riscv-collab/riscv-edk2/commits/devel-boot-kernel

**Comment by yqszxx** [comment]
Thank you! I'll try that branch!
